workflows:
  ios-build:
    name: iOS Build Workflow
    working_directory: DeepBriscaApp
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Update Cocoapods
        script: |
          sudo gem install cocoapods -v '1.12.0' # Or latest version
          pod repo update
      - name: Flutter pub get
        script: flutter pub get
      - name: Install Pods
        script: cd ios && pod install
      - name: Flutter build ios
        script: flutter build ios --release --no-codesign --archive
    artifacts:
      - build/ios/archive/*.xcarchive # Archive for future reference
      - build/ios/ipa/*.ipa # IPA will be generated during archiving